const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.DrawingCanvas,
		C3.Behaviors.Tween,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.bound,
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Plugins.NinePatch,
		C3.Plugins.Particles,
		C3.Plugins.Keyboard,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Plugins.Touch,
		C3.Plugins.Button,
		C3.Plugins.sliderbar,
		C3.Plugins.HTMLElement,
		C3.Behaviors.EightDir,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.DrawingCanvas.Acts.SetInstanceVar,
		C3.Plugins.DrawingCanvas.Acts.SetSize,
		C3.Plugins.DrawingCanvas.Acts.PasteObject,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.DrawingCanvas.Acts.MoveToTop,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.DrawingCanvas.Exps.Angle,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.DrawingCanvas.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.NinePatch.Cnds.PickByUID,
		C3.Plugins.NinePatch.Acts.SetBoolInstanceVar,
		C3.Plugins.DrawingCanvas.Acts.SetBoolInstanceVar,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.NinePatch.Cnds.PickDistance,
		C3.Plugins.DrawingCanvas.Exps.X,
		C3.Plugins.DrawingCanvas.Exps.Y,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.NinePatch.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.NinePatch.Exps.UID,
		C3.Plugins.DrawingCanvas.Acts.SetPos,
		C3.Plugins.DrawingCanvas.Exps.Width,
		C3.Plugins.DrawingCanvas.Exps.Height,
		C3.Plugins.DrawingCanvas.Acts.MoveToBottom,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.DrawingCanvas.Exps.Count,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Acts.SetLayoutAngle,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Text.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{Index: 0},
	{Snapped: 0},
	{GridBlockUID: 0},
	{Tween: 0},
	{DragDrop: 0},
	{邊界約束: 0},
	{Piece: 0},
	{SourceImage: 0},
	{Background: 0},
	{GridBlock: 0},
	{PickEffect: 0},
	{GameManager: 0},
	{SplashGlow: 0},
	{Flash: 0},
	{WinGlow: 0},
	{Frame: 0},
	{Keyboard: 0},
	{Fade: 0},
	{Tutorial: 0},
	{nextlevel: 0},
	{Touch: 0},
	{start: 0},
	{首頁: 0},
	{按鈕: 0},
	{滑動條: 0},
	{HTML元素: 0},
	{Sprite: 0},
	{"8方向": 0},
	{黑長尾雉: 0},
	{熊鷹A: 0},
	{滑動條2: 0},
	{按鈕2: 0},
	{黑長尾雉A: 0},
	{fivecolorbiradA: 0},
	{石虎A: 0},
	{臺灣水鹿A: 0},
	{穿山甲A: 0},
	{臺灣水鹿2: 0},
	{restar: 0},
	{text: 0},
	{notinportan: 0},
	{Text2: 0},
	{shap: 0},
	{huangin: 0},
	{behavier: 0},
	{"9patch": 0},
	{first: 0},
	{seconcd: 0},
	{third: 0},
	{BG1: 0},
	{"9patch2": 0},
	{BG2: 0},
	{blackbord: 0},
	{PiecesPerLine: 0},
	{PiecesWidth: 0},
	{PiecesHeight: 0},
	{SpawnMargin: 0},
	{SnapDistance: 0},
	{CurrentIndex: 0},
	{Count: 0},
	{Duration: 0},
	{Strength: 0}
];

self.InstanceType = {
	Piece: class extends self.IDrawingCanvasInstance {},
	SourceImage: class extends self.ISpriteInstance {},
	Background: class extends self.ITiledBackgroundInstance {},
	GridBlock: class extends self.IWorldInstance {},
	PickEffect: class extends self.IWorldInstance {},
	GameManager: class extends self.ISpriteInstance {},
	SplashGlow: class extends self.IParticlesInstance {},
	Flash: class extends self.ITiledBackgroundInstance {},
	WinGlow: class extends self.IParticlesInstance {},
	Frame: class extends self.IWorldInstance {},
	Keyboard: class extends self.IInstance {},
	Tutorial: class extends self.ISpriteFontInstance {},
	nextlevel: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	start: class extends self.ISpriteInstance {},
	首頁: class extends self.ISpriteInstance {},
	按鈕: class extends self.IButtonInstance {},
	滑動條: class extends self.ISliderBarInstance {},
	HTML元素: class extends self.IHTMLElementInstance {},
	Sprite: class extends self.ISpriteInstance {},
	黑長尾雉: class extends self.ISpriteInstance {},
	熊鷹A: class extends self.ISpriteInstance {},
	滑動條2: class extends self.ISliderBarInstance {},
	按鈕2: class extends self.IButtonInstance {},
	黑長尾雉A: class extends self.ISpriteInstance {},
	fivecolorbiradA: class extends self.ISpriteInstance {},
	石虎A: class extends self.ISpriteInstance {},
	臺灣水鹿A: class extends self.ISpriteInstance {},
	穿山甲A: class extends self.ISpriteInstance {},
	臺灣水鹿2: class extends self.ISpriteInstance {},
	restar: class extends self.ISpriteInstance {},
	text: class extends self.ITextInstance {},
	notinportan: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	shap: class extends self.IButtonInstance {},
	huangin: class extends self.IButtonInstance {},
	behavier: class extends self.IButtonInstance {},
	_9patch: class extends self.IWorldInstance {},
	first: class extends self.ITextInstance {},
	seconcd: class extends self.ITextInstance {},
	third: class extends self.ITextInstance {},
	BG1: class extends self.ISpriteInstance {},
	_9patch2: class extends self.IWorldInstance {},
	BG2: class extends self.IWorldInstance {},
	blackbord: class extends self.IWorldInstance {}
}